application: miniblog
version: 3
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: 7d

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: favicon\.ico

- url: /blog/(.*)
  script: main.app

- url: /(.*?)/(.*)
  static_files: static/\1/\2
  upload: static/(.*)

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
